# ~/.config/environment.d/xdg.conf

XDG_CONFIG_HOME=${HOME}/.config
XDG_CACHE_HOME=${HOME}/.cache
XDG_DATA_HOME=${HOME}/.local/share
XDG_STATE_HOME=${HOME}/.local/state

NPM_CONFIG_CACHE=${XDG_CACHE_HOME}/npm
ANDROID_USER_HOME=${XDG_DATA_HOME}/android
__GL_SHADER_DISK_CACHE_PATH=${XDG_CACHE_HOME}/nvidia/GLCache
CUDA_CACHE_PATH=${XDG_CACHE_HOME}/nvidia/ComputeCache
GNUPGHOME=${XDG_DATA_HOME}/gnupg
PULSE_CLIENTCONFIG=${XDG_CONFIG_HOME}/pulse/client.conf
PULSE_COOKIE=${XDG_CONFIG_HOME}/pulse/cookie
MISE_CARGO_HOME=${XDG_DATA_HOME}/cargo
MISE_RUSTUP_HOME=${XDG_DATA_HOME}/rustup
CODEX_HOME=${XDG_DATA_HOME}/codex
RENPY_PATH_TO_SAVES=${XDG_DATA_HOME}/renpy
ANDROID_HOME=${XDG_DATA_HOME}/Android/Sdk
FVM_CACHE_PATH=${XDG_CACHE_HOME}/fvm
FVM_GIT_CACHE_PATH=${XDG_CACHE_HOME}/fvm/git-cache
PUB_CACHE=${XDG_CACHE_HOME}/fvm/pub-cache
